logging 12

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,7 +36,7 @@ jobs:
       - name: Output Terraform Outputs to JSON file
         run: |
           echo "Outputting Terraform Outputs to JSON file..."
-          terraform output -json > tf_outputs.json
+          terraform output -json | tee tf_outputs.json
 
       - name: Display raw content of tf_outputs.json
         run: |
@@ -46,7 +46,12 @@ jobs:
       - name: Validate JSON structure of tf_outputs.json
         run: |
           echo "Validating JSON structure of tf_outputs.json..."
-          jq empty tf_outputs.json || { echo "Invalid JSON structure"; exit 1; }
+          if ! jq empty tf_outputs.json; then
+            echo "Invalid JSON structure"
+            exit 1
+          else
+            echo "JSON structure is valid."
+          fi
 
       - name: Parse Terraform Outputs and Set Environment Variables
         id: parse_outputs
@@ -70,7 +75,7 @@ jobs:
       - name: Configure App Service Environment Variables
         run: |
           echo "Configuring App Service Environment Variables"
-          az webapp config appsettings set --name nodejs-app-${{ steps.output.outputs.random_pet_name }} --resource-group myResourceGroup-${{ steps.output.outputs.random_pet_name }} --settings \
+          az webapp config appsettings set --name nodejs-app-${{ steps.parse_outputs.outputs.random_pet_name }} --resource-group myResourceGroup-${{ steps.parse_outputs.outputs.random_pet_name }} --settings \
             PROD_DB_USER=${{ env.PROD_DB_USER }} \
             PROD_DB_PASSWORD=${{ env.PROD_DB_PASSWORD }} \
             PROD_DB_HOST=${{ env.PROD_DB_HOST }} \
